ALTER TABLE bookings ADD COLUMN IF NOT EXISTS overstay_notified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS overstay_reminded_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS actual_vacated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS vacated_via VARCHAR(30)
    CHECK (vacated_via IN ('SELF', 'OWNER_REQUEST_ACCEPTED', 'VACATE_TOKEN', 'OWNER_RELEASED_AFTER_EXPIRY', 'SYSTEM'));
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS overstay_minutes INT DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS rebook_group_id UUID;
