-- V7: Add vacate_token to bookings table to support dual-confirmation seat vacation

ALTER TABLE bookings ADD COLUMN vacate_token VARCHAR(10);
COMMENT ON COLUMN bookings.vacate_token IS 'Optional 8-digit token generated by student and provided to owner to confirm seat vacating';
